config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/activities' => 'activities#index'
  get '/activities/new' => 'activities#new'
  post 'activities' => 'activities#create'
  get '/activities/:id/edit' => 'activities#edit', as: :edit_activity
  patch '/activities/:id' => 'activities#update'
  resources :activities

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	def index
		@activities = Activity.all
	end
	def new
		@activity = Activity.new
	end
	def create
		@activity = Activity.new(activity_params)
		if @activity.save
			redirect_to '/activities'
		else
			render 'new'
		end
	end

	def show
		@activity = Activity.find(params[:id])
	end

	def edit
		@activity = Activity.find(params[:id])
	end

	def update
		@activity = Activity.find(params[:id])
		if @activity.update_attributes(activity_params)
			redirect_to(:action => 'show', :id => @activity.id)
		else
			render 'edit'
		end
	end

	private
		def activity_params
			params.require(:activity).permit(:activity_name)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def welcome

	end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/edit.html.erb
<%= form_for(@activity) do |a| %>
	<div class="field">
		<%= a.text_area :activity_name %>
	</div>
	<div class="actions">
		<%= a.submit "Submit edit" %>
	</div>
<% end %>

app/views/activities/index.html.erb
<h2>This is the INDEX page for activities. Get the WHOLE list. All of it.</h2>

<% @activities.each do |activity| %>
<div class="activity">
	<%= link_to(activity) do %>
		<p class="name"><%= activity.activity_name %></p>
		<p class="time_available"><%= activity.minutes_available %></p>
	<% end %>
</div>
<% end %>

<%= link_to 'New Activity', "/activities/new" %>
<h2>End list.</h2>

app/views/activities/new.html.erb
<div class="header">
  <div class="container">
    <h1>Messenger</h1>
  </div>
</div>


<h1>New activity</h1>
<%= form_for(@activity) do |f| %>
	<div class="field">
		<%= f.label :message %><br>
		<%= f.text_area :activity_name %>
	</div>
	<div class="actions">
		<%= f.submit "Create" %>
	</div>
<% end %>

app/views/activities/show.html.erb
<%= @activity.activity_name %><br>
<%= @activity.location %> <br>

<%= link_to "Edit", edit_activity_path(@activity) %> <br>
<%= link_to 'Return Home', "/activities" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test001</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Test begins...</h1>
<%= yield %>
<h3>Test ends.</h3>

</body>
</html>

app/views/pages/welcome.html.erb
<h2>Test happening here!</h2>